title: "Zhenfeng Sun"
author: "Zhenfeng Sun"
description: "Personal Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
#   - {file: "index.html"}
#   - {file: "README.md"}
  - {title: "Home", file: "Home.md"}
  - {title: "Research", file:"Research.md"}
  - {title: "Publications", file:"Publications.md"}
  - {title: "Personal Projects", file:"Personal-Projects.md"}
  - {title: "Experience", file:"Experience.md"}
  - {title: "Awards", file:"Awards.md"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:goku_tech@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/goku0401"}
  - {title: Google Schoolar, icon: rss, url: "https://scholar.google.co.uk/citations?user=XtoBqIkAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
